# Generated by Django 5.2.4 on 2025-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="singer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-07-08 10:40"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="singer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="singer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
