# Generated by Django 5.2.4 on 2025-07-15 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_singer_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singer",
            name="image",
        ),
        migrations.CreateModel(
            name="SingerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="singer_images/")),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="music.singer",
                    ),
                ),
            ],
        ),
    ]
